require 'rails_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

RSpec.describe ProjectDonorsController, type: :controller do

  # This should return the minimal set of attributes required to create a valid
  # ProjectDonor. As you add validations to ProjectDonor, be sure to
  # adjust the attributes here as well.
  let(:valid_attributes) {
    skip("Add a hash of attributes valid for your model")
  }

  let(:invalid_attributes) {
    skip("Add a hash of attributes invalid for your model")
  }

  # This should return the minimal set of values that should be in the session
  # in order to pass any filters (e.g. authentication) defined in
  # ProjectDonorsController. Be sure to keep this updated too.
  let(:valid_session) { {} }

  describe "GET #index" do
    it "assigns all project_donors as @project_donors" do
      project_donor = ProjectDonor.create! valid_attributes
      get :index, {}, valid_session
      expect(assigns(:project_donors)).to eq([project_donor])
    end
  end

  describe "GET #show" do
    it "assigns the requested project_donor as @project_donor" do
      project_donor = ProjectDonor.create! valid_attributes
      get :show, {:id => project_donor.to_param}, valid_session
      expect(assigns(:project_donor)).to eq(project_donor)
    end
  end

  describe "GET #new" do
    it "assigns a new project_donor as @project_donor" do
      get :new, {}, valid_session
      expect(assigns(:project_donor)).to be_a_new(ProjectDonor)
    end
  end

  describe "GET #edit" do
    it "assigns the requested project_donor as @project_donor" do
      project_donor = ProjectDonor.create! valid_attributes
      get :edit, {:id => project_donor.to_param}, valid_session
      expect(assigns(:project_donor)).to eq(project_donor)
    end
  end

  describe "POST #create" do
    context "with valid params" do
      it "creates a new ProjectDonor" do
        expect {
          post :create, {:project_donor => valid_attributes}, valid_session
        }.to change(ProjectDonor, :count).by(1)
      end

      it "assigns a newly created project_donor as @project_donor" do
        post :create, {:project_donor => valid_attributes}, valid_session
        expect(assigns(:project_donor)).to be_a(ProjectDonor)
        expect(assigns(:project_donor)).to be_persisted
      end

      it "redirects to the created project_donor" do
        post :create, {:project_donor => valid_attributes}, valid_session
        expect(response).to redirect_to(ProjectDonor.last)
      end
    end

    context "with invalid params" do
      it "assigns a newly created but unsaved project_donor as @project_donor" do
        post :create, {:project_donor => invalid_attributes}, valid_session
        expect(assigns(:project_donor)).to be_a_new(ProjectDonor)
      end

      it "re-renders the 'new' template" do
        post :create, {:project_donor => invalid_attributes}, valid_session
        expect(response).to render_template("new")
      end
    end
  end

  describe "PUT #update" do
    context "with valid params" do
      let(:new_attributes) {
        skip("Add a hash of attributes valid for your model")
      }

      it "updates the requested project_donor" do
        project_donor = ProjectDonor.create! valid_attributes
        put :update, {:id => project_donor.to_param, :project_donor => new_attributes}, valid_session
        project_donor.reload
        skip("Add assertions for updated state")
      end

      it "assigns the requested project_donor as @project_donor" do
        project_donor = ProjectDonor.create! valid_attributes
        put :update, {:id => project_donor.to_param, :project_donor => valid_attributes}, valid_session
        expect(assigns(:project_donor)).to eq(project_donor)
      end

      it "redirects to the project_donor" do
        project_donor = ProjectDonor.create! valid_attributes
        put :update, {:id => project_donor.to_param, :project_donor => valid_attributes}, valid_session
        expect(response).to redirect_to(project_donor)
      end
    end

    context "with invalid params" do
      it "assigns the project_donor as @project_donor" do
        project_donor = ProjectDonor.create! valid_attributes
        put :update, {:id => project_donor.to_param, :project_donor => invalid_attributes}, valid_session
        expect(assigns(:project_donor)).to eq(project_donor)
      end

      it "re-renders the 'edit' template" do
        project_donor = ProjectDonor.create! valid_attributes
        put :update, {:id => project_donor.to_param, :project_donor => invalid_attributes}, valid_session
        expect(response).to render_template("edit")
      end
    end
  end

  describe "DELETE #destroy" do
    it "destroys the requested project_donor" do
      project_donor = ProjectDonor.create! valid_attributes
      expect {
        delete :destroy, {:id => project_donor.to_param}, valid_session
      }.to change(ProjectDonor, :count).by(-1)
    end

    it "redirects to the project_donors list" do
      project_donor = ProjectDonor.create! valid_attributes
      delete :destroy, {:id => project_donor.to_param}, valid_session
      expect(response).to redirect_to(project_donors_url)
    end
  end

end
